### ISSUE TITLE
Page - Asistentes

### ISSUE THREAD

**Issue by alexgordon25** [wpnicaragua/WCMGA2018-Landing-Custom-CSS#12]
This page will get like 400 attendee, I think it should be better to remove the sidebar from it.
![image](https://user-images.githubusercontent.com/2489382/38281523-22eb5d4c-3768-11e8-9329-31f003eabebd.png)

**Comment by alexcuadra** [comment]
working on it

**Comment by alexcuadra** [comment]
done
